apiVersion: v1
kind: ConfigMap
metadata:
  name: timesheet-config
  namespace: chap4
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-serv:3306/timesheetdb?useSSL=false&allowPublicKeyRetrieval=true

